{"name": "test_login_fail[case0]", "status": "passed", "attachments": [{"name": "log", "source": "1f2167e1-38b9-48f8-b4a9-b93a2762e1f7-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'title': '手机号错误', 'phone': '17610772809', 'pwd': 'zhangcy4860801', 'expected': '用户不存在'}"}], "start": 1604474242895, "stop": 1604474243687, "uuid": "7b8effa8-48e9-4652-afbf-413d428a2064", "historyId": "7162a1bb48dabadd6569761fb92bd610", "testCaseId": "2a81b10f036ab8a26bb49e6669c3c22b", "fullName": "testcase.test_01login.TestLogin#test_login_fail", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_01login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ZBMAC-C02WD0XQH.local"}, {"name": "thread", "value": "18542-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_01login"}]}