{"name": "test_login_fail[case0]", "status": "passed", "attachments": [{"name": "log", "source": "1875a9e6-eef9-4a45-bafe-0cc290027acd-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'title': '手机号错误', 'phone': '17610772809', 'pwd': 'zhangcy4860801', 'expected': '用户不存在'}"}], "start": 1604461894459, "stop": 1604461896180, "uuid": "a09c43f8-4a81-4797-bded-240e4834e8e5", "historyId": "7162a1bb48dabadd6569761fb92bd610", "testCaseId": "2a81b10f036ab8a26bb49e6669c3c22b", "fullName": "testcase.test_01login.TestLogin#test_login_fail", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_01login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ZBMAC-C02WD0XQH.local"}, {"name": "thread", "value": "55631-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_01login"}]}