{"name": "test_login_fail[case0]", "status": "passed", "attachments": [{"name": "log", "source": "fdb53033-fbde-4814-ae60-71fae78aa070-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "{'title': '手机号错误', 'phone': '17610772809', 'pwd': 'zhangcy4860801', 'expected': '用户不存在'}"}], "start": 1604473484190, "stop": 1604473484861, "uuid": "5fb1c52d-64d6-425c-9a01-3dbb68d36acd", "historyId": "7162a1bb48dabadd6569761fb92bd610", "testCaseId": "2a81b10f036ab8a26bb49e6669c3c22b", "fullName": "testcase.test_01login.TestLogin#test_login_fail", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_01login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "ZBMAC-C02WD0XQH.local"}, {"name": "thread", "value": "14501-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_01login"}]}